---
- name: Include vars for OpenVPN installation
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/empty.yml"

- name: Set facts
  ansible.builtin.import_tasks: set_facts.yml

- name: Uninstall OpenVPN
  ansible.builtin.import_tasks: uninstall.yml
  when: openvpn_uninstall

- name: Install OpenVPN
  ansible.builtin.import_tasks: install.yml
  tags:
    - install

- name: Copy or Generate server keys
  ansible.builtin.import_tasks: server_keys.yml

# ignoreerrors is required for CentOS/RHEL 6
# http://serverfault.com/questions/477718/sysctl-p-etc-sysctl-conf-returns-error
- name: Enable ipv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    ignoreerrors: true
  failed_when: false
  when: not ci_build

- name: Enable ipv6 forwarding
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    ignoreerrors: true
  when: openvpn_server_ipv6_network is defined and not ci_build

- name: Detect firewall type
  ansible.builtin.import_tasks: firewall.yml
  when:
    - not ci_build
    - manage_firewall_rules
  tags:
    - firewall

- name: Configure SELinux
  ansible.builtin.import_tasks: selinux.yml
  when:
    - ansible_selinux.status == "enabled"

- name: Compare existing certs against 'clients' variable
  ansible.builtin.import_tasks: cert_sync_detection.yml
  when: openvpn_sync_certs
  tags:
    - sync_certs

- name: Generate client configs
  ansible.builtin.import_tasks: client_keys.yml
  when: clients is defined

- name: Generate revocation list and clean up
  ansible.builtin.import_tasks: revocation.yml
  when: >-
    (openvpn_revoke_these_certs is defined)
    or
    (openvpn_sync_certs and cert_sync_certs_to_revoke.stdout_lines | length > 0)

- name: Configure OpenVPN server
  ansible.builtin.import_tasks: config.yml

- name: Set OpenVPN service
  ansible.builtin.lineinfile:
    path: "/etc/systemd/system/multi-user.target.wants/{{ openvpn_service_name }}"
    line: ExecStart=/usr/sbin/openvpn --status %t/openvpn-server/status-%i.log --status-version 2 --cipher AES-256-GCM --ncp-ciphers AES-256-GCM:AES-128-GCM:AES-256-CBC:AES-128-CBC:BF-CBC --config %i.conf
    state: present
