---
- name: Converge
  hosts: all
  tasks:

    - name: Install firewalld
      ansible.builtin.package:
        name: '{{ item }}'
        state: present
      become: true
      with_items:
        - firewalld
        - ipset
      when:
        - ansible_virtualization_type not in ['docker', 'container']
        - ansible_service_mgr == 'systemd'

    - name: Start firewalld
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true
      become: true
      when:
        - ansible_virtualization_type not in ['docker', 'container']
        - ansible_service_mgr == 'systemd'

    - name: Run val1141 fork of bwinfosec.openvpn
      ansible.builtin.include_role:
        name: ansible-role-openvpn
