name: Molecule Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - centos
          - ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: converge
          molecule_args: --scenario-name ${{ matrix.scenario }}
        env:
          ANSIBLE_FORCE_COLOR: '1'
