name: Publish Ansible Role to Galaxy

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish on Ansible Galaxy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Release Ansible Role to Galaxy
        uses: hspaans/ansible-galaxy-action@v2.1.0
        with:
          api_key: ${{ secrets.galaxy_api_key }}
